from dispatcher.processors.kick_processor import kick_processor
from dispatcher.processors.mute_processor import mute_processor
from dispatcher.processors.view_managers_processor import view_managers_processor
from dispatcher.processors.quit_processor import quit_processor
from dispatcher.processors.promote_processor import promote_processor
from dispatcher.processors.send_all_processor import send_all_processor
from dispatcher.processors.private_message_processor import private_message_processor
from dispatcher.processors.request_validator import request_validator